version: '2'
services:
    oplusudp-app:
        image: oplusudp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://oplusudp-mysql:3306/oplusudp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    oplusudp-mysql:
        extends:
            file: mysql.yml
            service: oplusudp-mysql
